-- VEXA BACKEND: publishing workflow, creators, comments, reactions and views.
-- Run once in Supabase SQL Editor.

-- Creator profiles. Existing profile tables are preserved; missing columns are added.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists role text not null default 'user';

-- Published/pending workflow for videos.
alter table public.videos add column if not exists uploader_id uuid references auth.users(id) on delete set null;
alter table public.videos add column if not exists status text not null default 'published';
alter table public.videos add column if not exists submitted_at timestamptz default now();
alter table public.videos add column if not exists approved_at timestamptz;
alter table public.videos add column if not exists approved_by uuid references auth.users(id) on delete set null;
alter table public.videos add column if not exists uploader_name text;

-- Photos use the same moderation fields when the table exists.
do $$ begin
  if to_regclass('public.photos') is not null then
    execute 'alter table public.photos add column if not exists uploader_id uuid references auth.users(id) on delete set null';
    execute 'alter table public.photos add column if not exists status text not null default ''published''';
    execute 'alter table public.photos add column if not exists submitted_at timestamptz default now()';
    execute 'alter table public.photos add column if not exists approved_at timestamptz';
    execute 'alter table public.photos add column if not exists approved_by uuid references auth.users(id) on delete set null';
    execute 'alter table public.photos add column if not exists uploader_name text';
  end if;
end $$;

create or replace function public.is_vexa_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'); $$;
grant execute on function public.is_vexa_admin() to anon, authenticated;

-- New users get a profile from auth metadata.
create or replace function public.handle_vexa_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$ begin
  insert into public.profiles(id,username,display_name) values(new.id,new.raw_user_meta_data->>'username',coalesce(new.raw_user_meta_data->>'display_name',new.raw_user_meta_data->>'username')) on conflict(id) do update set username=coalesce(excluded.username,profiles.username),display_name=coalesce(excluded.display_name,profiles.display_name);
  return new;
end $$;
drop trigger if exists on_auth_user_created_vexa on auth.users;
create trigger on_auth_user_created_vexa after insert on auth.users for each row execute function public.handle_vexa_new_user();

-- Public catalog view: only approved/published videos are exposed to normal users.
create or replace view public.vexa_published_videos as
select v.* from public.videos v where coalesce(v.status,'published')='published';

-- Comments are moderated before public display.
create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  guest_name text,
  body text not null check (length(trim(body)) between 1 and 1000),
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  check (user_id is not null or length(trim(coalesce(guest_name,''))) between 1 and 80)
);

alter table public.video_comments alter column user_id drop not null;
alter table public.video_comments add column if not exists guest_name text;
create index if not exists video_comments_video_idx on public.video_comments(video_id,created_at desc);
alter table public.video_comments enable row level security;
drop policy if exists "comments_public_approved" on public.video_comments;
create policy "comments_public_approved" on public.video_comments for select using (status='approved' or auth.uid()=user_id or public.is_vexa_admin());
drop policy if exists "comments_insert_own" on public.video_comments;
drop policy if exists "comments_insert_guest" on public.video_comments;
create policy "comments_insert_own" on public.video_comments for insert to authenticated with check(auth.uid()=user_id and status='pending');
create policy "comments_insert_guest" on public.video_comments for insert to anon, authenticated with check(user_id is null and length(trim(coalesce(guest_name,''))) between 1 and 80 and status='pending');
drop policy if exists "comments_admin_update" on public.video_comments;
create policy "comments_admin_update" on public.video_comments for update to authenticated using(public.is_vexa_admin()) with check(public.is_vexa_admin());
drop policy if exists "comments_admin_delete" on public.video_comments;
create policy "comments_admin_delete" on public.video_comments for delete to authenticated using(public.is_vexa_admin());

-- Reactions.
create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz not null default now(),
  unique(video_id,user_id)
);
alter table public.reactions enable row level security;
drop policy if exists "reactions_select_public" on public.reactions;
create policy "reactions_select_public" on public.reactions for select using (true);
drop policy if exists "reactions_insert_own" on public.reactions;
create policy "reactions_insert_own" on public.reactions for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "reactions_update_own" on public.reactions;
create policy "reactions_update_own" on public.reactions for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "reactions_delete_own" on public.reactions;
create policy "reactions_delete_own" on public.reactions for delete to authenticated using(auth.uid()=user_id);

create or replace function public.set_video_reaction(p_video_id bigint,p_reaction text)
returns table(likes bigint,dislikes bigint) language plpgsql security definer set search_path=public as $$
declare old_reaction text;
begin
  if auth.uid() is null then raise exception 'You must be signed in to react'; end if;
  if p_reaction not in ('like','dislike') then raise exception 'Invalid reaction'; end if;
  select reaction into old_reaction from public.reactions where video_id=p_video_id and user_id=auth.uid();
  if old_reaction=p_reaction then delete from public.reactions where video_id=p_video_id and user_id=auth.uid();
  else insert into public.reactions(video_id,user_id,reaction) values(p_video_id,auth.uid(),p_reaction) on conflict(video_id,user_id) do update set reaction=excluded.reaction,created_at=now(); end if;
  update public.videos set likes=(select count(*) from public.reactions where video_id=public.videos.id and reaction='like'),dislikes=(select count(*) from public.reactions where video_id=public.videos.id and reaction='dislike') where id=p_video_id;
  return query select v.likes,v.dislikes from public.videos v where v.id=p_video_id;
end $$;
grant execute on function public.set_video_reaction(bigint,text) to authenticated;

-- View tracking.
create table if not exists public.video_view_events(id bigint generated by default as identity primary key,video_id bigint not null references public.videos(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
alter table public.video_view_events enable row level security;
drop policy if exists "view_events_insert_authenticated" on public.video_view_events;
create policy "view_events_insert_authenticated" on public.video_view_events for insert to authenticated with check(auth.uid()=user_id);
create or replace function public.record_video_view(p_video_id bigint) returns bigint language plpgsql security definer set search_path=public as $$ declare new_views bigint; begin insert into public.video_view_events(video_id,user_id) values(p_video_id,auth.uid()); update public.videos set views=coalesce(views,0)+1 where id=p_video_id returning views into new_views; return new_views; end $$;
grant execute on function public.record_video_view(bigint) to authenticated;

-- Admin moderation helpers.
create or replace function public.vexa_moderate_video(p_video_id bigint,p_status text)
returns void language plpgsql security definer set search_path=public as $$ begin
  if not public.is_vexa_admin() then raise exception 'Admin access required'; end if;
  if p_status not in ('published','rejected','pending') then raise exception 'Invalid status'; end if;
  update public.videos set status=p_status,approved_at=case when p_status='published' then now() else approved_at end,approved_by=case when p_status='published' then auth.uid() else approved_by end where id=p_video_id;
end $$;
grant execute on function public.vexa_moderate_video(bigint,text) to authenticated;
