-- VEXA BACKEND MIGRATION
-- Run in Supabase SQL Editor.
-- This is designed to work with the existing videos/categories/profiles tables.

-- Reactions: one reaction per signed-in user per video.
create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz not null default now(),
  unique(video_id,user_id)
);

create index if not exists reactions_video_idx on public.reactions(video_id);
create index if not exists reactions_user_idx on public.reactions(user_id);

alter table public.reactions enable row level security;

drop policy if exists "reactions_select_public" on public.reactions;
create policy "reactions_select_public" on public.reactions
for select using (true);

drop policy if exists "reactions_insert_own" on public.reactions;
create policy "reactions_insert_own" on public.reactions
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "reactions_update_own" on public.reactions;
create policy "reactions_update_own" on public.reactions
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "reactions_delete_own" on public.reactions;
create policy "reactions_delete_own" on public.reactions
for delete to authenticated using (auth.uid() = user_id);


-- Reaction RPC.
create or replace function public.set_video_reaction(
  p_video_id bigint,
  p_reaction text
)
returns table(likes bigint, dislikes bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  old_reaction text;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to react';
  end if;

  if p_reaction not in ('like','dislike') then
    raise exception 'Invalid reaction';
  end if;

  select r.reaction into old_reaction
  from public.reactions r
  where r.video_id = p_video_id and r.user_id = auth.uid();

  if old_reaction = p_reaction then
    delete from public.reactions
    where video_id = p_video_id and user_id = auth.uid();
  else
    insert into public.reactions(video_id,user_id,reaction)
    values(p_video_id,auth.uid(),p_reaction)
    on conflict(video_id,user_id)
    do update set reaction=excluded.reaction, created_at=now();
  end if;

  update public.videos v
  set likes = (select count(*) from public.reactions r where r.video_id=v.id and r.reaction='like'),
      dislikes = (select count(*) from public.reactions r where r.video_id=v.id and r.reaction='dislike')
  where v.id=p_video_id;

  return query
  select v.likes, v.dislikes from public.videos v where v.id=p_video_id;
end;
$$;

grant execute on function public.set_video_reaction(bigint,text) to authenticated;


-- View tracking. This version records an authenticated user's view.
create table if not exists public.video_view_events (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists video_view_events_video_idx on public.video_view_events(video_id);
create index if not exists video_view_events_user_idx on public.video_view_events(user_id);

alter table public.video_view_events enable row level security;

drop policy if exists "view_events_insert_authenticated" on public.video_view_events;
create policy "view_events_insert_authenticated" on public.video_view_events
for insert to authenticated with check (auth.uid() = user_id);

create or replace function public.record_video_view(p_video_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_views bigint;
begin
  insert into public.video_view_events(video_id,user_id)
  values(p_video_id,auth.uid());

  update public.videos
  set views=views+1
  where id=p_video_id
  returning views into new_views;

  return new_views;
end;
$$;

grant execute on function public.record_video_view(bigint) to authenticated;


-- Keep your existing trending/latest views.
-- Optional published-only versions can be added after you confirm
-- the exact status values used in your videos table.
