-- Vexa v12: photo reactions
-- Run this once in the Supabase SQL editor for the photo Like/Dislike counts to persist.

alter table public.photos add column if not exists likes bigint not null default 0;
alter table public.photos add column if not exists dislikes bigint not null default 0;

create table if not exists public.photo_reactions (
  id bigint generated by default as identity primary key,
  photo_id bigint not null references public.photos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz not null default now(),
  unique(photo_id,user_id)
);

alter table public.photo_reactions enable row level security;

drop policy if exists "photo_reactions_select_public" on public.photo_reactions;
create policy "photo_reactions_select_public" on public.photo_reactions
for select using (true);

drop policy if exists "photo_reactions_insert_own" on public.photo_reactions;
create policy "photo_reactions_insert_own" on public.photo_reactions
for insert to authenticated with check (auth.uid()=user_id);

drop policy if exists "photo_reactions_update_own" on public.photo_reactions;
create policy "photo_reactions_update_own" on public.photo_reactions
for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "photo_reactions_delete_own" on public.photo_reactions;
create policy "photo_reactions_delete_own" on public.photo_reactions
for delete to authenticated using (auth.uid()=user_id);

create or replace function public.set_photo_reaction(p_photo_id bigint,p_reaction text)
returns table(likes bigint,dislikes bigint)
language plpgsql security definer set search_path=public as $$
declare old_reaction text;
begin
  if auth.uid() is null then raise exception 'You must be signed in to react'; end if;
  if p_reaction not in ('like','dislike') then raise exception 'Invalid reaction'; end if;

  select reaction into old_reaction
  from public.photo_reactions
  where photo_id=p_photo_id and user_id=auth.uid();

  if old_reaction=p_reaction then
    delete from public.photo_reactions where photo_id=p_photo_id and user_id=auth.uid();
  else
    insert into public.photo_reactions(photo_id,user_id,reaction)
    values(p_photo_id,auth.uid(),p_reaction)
    on conflict(photo_id,user_id)
    do update set reaction=excluded.reaction,created_at=now();
  end if;

  update public.photos
  set likes=(select count(*) from public.photo_reactions where photo_id=public.photos.id and reaction='like'),
      dislikes=(select count(*) from public.photo_reactions where photo_id=public.photos.id and reaction='dislike')
  where id=p_photo_id;

  return query
  select p.likes,p.dislikes from public.photos p where p.id=p_photo_id;
end $$;

grant execute on function public.set_photo_reaction(bigint,text) to authenticated;

-- Initialize counts from any existing reactions if the table already contained rows.
update public.photos p
set likes=(select count(*) from public.photo_reactions r where r.photo_id=p.id and r.reaction='like'),
    dislikes=(select count(*) from public.photo_reactions r where r.photo_id=p.id and r.reaction='dislike');
