const DEMO_VIDEO_URL = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';
const DEMO_THUMB = 'https://placehold.co/1280x720/15171c/e9edf2?text=';

const demoTitles = [
  ['Beautiful Destinations','Travel','Explore beautiful places and scenic views from around the world.'],
  ['Full Body Workout','Fitness','A simple full-body workout demonstration for an active day.'],
  ['Dream Cars 2025','Automotive','A showcase of modern performance and luxury cars.'],
  ['Cool Gadgets You Need','Technology','Useful gadgets and technology worth knowing about.'],
  ['The Last Stand','Entertainment','A fictional action short made for this demo platform.'],
  ['A New Beginning','Lifestyle','A short inspirational story about starting again.'],
  ['Life is Funny','Comedy','A collection of light, family-friendly comedy moments.'],
  ['Epic Gameplay','Gaming','Highlights from an exciting gaming session.'],
  ['Chill Vibes','Music','Relaxing visuals for a calm listening session.'],
  ['Football Highlights','Sports','Fast-paced football highlights and memorable plays.'],
  ['Learn Python','Education','A beginner-friendly introduction to Python programming.'],
  ['Healthy Living','Lifestyle','Simple habits that can support an active lifestyle.'],
  ['Amazing Wildlife','Nature','Wildlife scenes from natural environments.'],
  ['Mountain Adventures','Travel','Mountain landscapes and outdoor adventures.'],
  ['Ocean Life','Nature','A look at fascinating life beneath the ocean surface.'],
  ['Forest Walks','Nature','Peaceful forest scenery and walking trails.'],
  ['Sunset Views','Travel','Beautiful sunset scenes from different locations.'],
  ['Street Food Tour','Food','A visual tour of popular street-food ideas.'],
  ['Photography Basics','Education','Beginner photography concepts explained simply.'],
  ['Home Studio Setup','Technology','Ideas for building a practical creator workspace.'],
  ['Basketball Skills','Sports','Basic basketball drills and practice ideas.'],
  ['Coding on Mobile','Technology','A look at learning and coding from a phone.'],
  ['Ocean Sunset','Nature','Calm ocean scenery at sunset.'],
  ['City Nights','Travel','Night-time city scenes and urban lights.'],
  ['Beginner Guitar','Music','Simple guitar practice for beginners.'],
  ['Easy Recipes','Food','Simple recipe inspiration for everyday cooking.'],
  ['Morning Routine','Lifestyle','A practical routine to start the day.'],
  ['Space Explained','Education','A beginner-friendly journey through space topics.'],
  ['Game Design Basics','Gaming','Core ideas behind designing a video game.'],
  ['Weekend Road Trip','Travel','A fictional road-trip showcase for the demo library.'],
  ['Creative Drawing','Education','Simple drawing exercises for beginners.'],
  ['Smart Home Ideas','Technology','Practical smart-home ideas and examples.'],
  ['Running Tips','Fitness','Basic running tips for new runners.'],
  ['Rainy Day Relaxation','Lifestyle','Relaxing rainy-day visuals and atmosphere.'],
  ['Wild Rivers','Nature','Scenic river landscapes and outdoor views.'],
  ['Football Skills','Sports','Practice drills for improving football skills.'],
  ['Web Design Basics','Education','A beginner introduction to responsive web design.'],
  ['Retro Gaming','Gaming','A celebration of classic gaming culture.'],
  ['Beach Walk','Travel','A calm walk along a beautiful beach.'],
  ['Tech News Recap','Technology','A fictional demo roundup of technology topics.'],
  ['Cooking Basics','Food','Simple cooking fundamentals for beginners.'],
  ['Evening Drive','Automotive','A fictional cinematic evening drive.'],
  ['Wildlife Close Up','Nature','Closer views of wildlife and natural scenery.'],
  ['Study With Me','Education','A calm study-session style video.'],
  ['Creative Workout','Fitness','A varied workout routine for an active day.'],
  ['Music Production 101','Music','An introduction to basic music production concepts.'],
  ['Travel Planning','Travel','Simple ideas for planning a memorable trip.'],
  ['Digital Art Basics','Education','A beginner look at creating digital artwork.'],
  ['Next-Gen Gadgets','Technology','A fictional showcase of new gadget concepts.'],
  ['Healthy Meals','Food','Simple healthy meal inspiration.'],
  ['Game Night','Gaming','Fun gaming-session highlights for the community.'],
  ['Nature Escape','Nature','Peaceful outdoor scenery for a quick escape.'],
  ['Weekend Fitness','Fitness','A short weekend exercise session.'],
  ['City Exploration','Travel','A fictional tour through a lively city.'],
  ['Learn HTML','Education','The basics of building a web page with HTML.'],
  ['Learn CSS','Education','The basics of styling responsive websites.'],
  ['Learn JavaScript','Education','An introduction to JavaScript for beginners.'],
  ['Creator Tips','Technology','Useful tips for new content creators.'],
  ['Motivation Minute','Lifestyle','A short positive message to start the day.'],
  ['Coastal Drive','Automotive','A scenic fictional drive beside the coast.']
];

window.VEXA_VIDEOS = demoTitles.map((item, index) => ({
  id: index + 1,
  title: item[0],
  category: item[1],
  description: item[2],
  tags: [item[1].toLowerCase(), 'vexa', 'demo'],
  thumbnail: DEMO_THUMB + encodeURIComponent(item[0]),
  preview: DEMO_VIDEO_URL,
  video: DEMO_VIDEO_URL,
  download: DEMO_VIDEO_URL,
  views: 350 + ((demoTitles.length - index) * 137),
  likes: 18 + ((demoTitles.length - index) * 3),
  dislikes: 1 + (index % 5),
  duration: '00:42',
  created_at: new Date(Date.now() - index * 86400000).toISOString()
}));
